name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '88.0.4324.96'

    - name: Start Xvfb
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 &

    - name: Start Web Server
      run: |
        npm start &
        sleep 5 # give Web server some time to bind to sockets, etc

    - name: Run Selenium Tests
      run: npx mocha test/test.spec.js